### PR TITLE
added automerge

### PR DESCRIPTION
**Pull request by subhangi2731**

### CODE REVIEW

**Comment by subhangi2731** [comment]
@Pranav016 I have made the pr here please check and merge

**Comment by Pranav016** [comment]
@all-contributors please add @subhangi2731 for code

**Comment by Pranav016** [comment]
@subhangi2731 I don't think the action is working..

**Comment by subhangi2731** [comment]
@Pranav016 I have not got points for this pr please tell this to gssoc team that u have merged my pr as this is a different repo which is not there in this list of gssoc projects

**Comment by Pranav016** [comment]
> @Pranav016 I have not got points for this pr please tell this to gssoc team that u have merged my pr as this is a different repo which is not there in this list of gssoc projects

This was just a test repo that the code you added on the main repo was working or not, it was not working so I did not merge it. This PR was merged only for test purpose, your code was not working so was not merged on the main repo, if it was working I've merged it on the WordNook repo and you would've got points for it.

**Comment by Pranav016** [comment]
> @subhangi2731 I don't think the action is working..

.

**Pull request merged**
